# Generated by Django 5.1 on 2024-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='created_at_in_DB',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
