# Generated by Django 5.1 on 2024-10-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_mindmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindmap',
            name='created_at',
        ),
    ]
