# Generated by Django 5.1 on 2024-09-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_api_key'),
    ]

    operations = [
    ]
