# Generated by Django 5.1 on 2024-08-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='step_and_POC',
            new_name='steps_and_POC',
        ),
    ]
