# Generated by Django 5.1 on 2024-08-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0002_rename_step_and_poc_report_steps_and_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.CharField(editable=False, max_length=600),
        ),
    ]
