# Generated by Django 5.1 on 2024-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0003_alter_report_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.CharField(max_length=600),
        ),
    ]
