# Generated by Django 5.1 on 2024-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0004_report_slug_alter_report_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.TextField(max_length=600),
        ),
    ]
