# Generated by Django 5.1 on 2024-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0005_alter_report_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.TextField(),
        ),
    ]
