# Generated by Django 5.1 on 2024-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0006_alter_report_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='steps_and_POC',
            field=models.TextField(help_text='steps and POC will be use As you write them in the report', max_length=500),
        ),
    ]
