# Generated by Django 5.1 on 2024-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genReport', '0007_alter_report_steps_and_poc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='steps_and_POC',
        ),
        migrations.AddField(
            model_name='report',
            name='POC',
            field=models.TextField(default=1, help_text='Please enter the Proof of Concept (POC) exactly as you would like it to appear in the report. The system will not modify this field.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='step_to_reproduce',
            field=models.TextField(default=1, help_text='Please enter the steps exactly as you would like them to appear in the report. The system will not modify these steps, so write them clearly.', max_length=500),
            preserve_default=False,
        ),
    ]
