# Generated by Django 5.1 on 2024-09-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_notes_slug_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
