# Generated by Django 5.1 on 2024-09-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Security_Indicators', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyVulnerabilities',
        ),
    ]
